import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import NavbarComponent from "@/components/navbar/NavbarComponent";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import { Suspense } from "react";
import Loading from "../loading";
import Error from "../error";
import FooterComponent from "@/components/footerComponent";
import SessionWrapper from "../SessionWrapper";
import StoreProvider from "../StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <SessionWrapper>
                <body className="flex justify-between flex-col" >
                    <StoreProvider>

                        <ErrorBoundary errorComponent={Error}>

                            <Suspense fallback={<Loading />}>{children}</Suspense>

                        </ErrorBoundary>

                    </StoreProvider>

                </body>
            </SessionWrapper>
        </html>




    );
}
